### ISSUE TITLE
Report same slot instead of same height as equivocation 

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/tlbc-monitor#16]
Belongs to: 

https://github.com/trustlines-network/project/issues/401
https://github.com/trustlines-network/project/issues/400

**Comment by weilbith** [comment]
@jannikluhn is there anything left since #17 has been merged?

**Comment by jannikluhn** [comment]
No, that should have been it.

**Comment by weilbith** [comment]
Awkward that auto-closing hasn't worked out. :man_shrugging:
