### ISSUE TITLE
Compare the performance of different index settings

### ISSUE THREAD

**Issue by weilbith** [trustlines-network/tlbc-monitor#2]
We should compare the performances of index settings. Because we read and write the data equally it is not totally obvious that using an index is better. It could be also better to only use an index on the height.

We should try at least the combinations:
- no index
- only height index
- both index

**Comment by weilbith** [comment]
I've created the following benchmark test:

To test only the performance of the database for reading and writing regarding indexed columns, a _Pytest_ case which creates bunches of blocks loop based with the maximum block fetching window (5.000), write them batched to the database and afterwards query the database related to the equivocation report for each new block that has been created (fetched). This should simulate the behavior of the `block_fetcher` on its initial sync state and afterwards calling the hooked equivocation reporter. 

Pseudocode:
```python
for round in range(0, x):
    branch = make_branch(5000)
    databse.insert_branch(branch)

    for block in branch:
        database.get_blocks_by_proposer_and_height(block.proposer, block.height)
```

Since the impact of the growing database size is of interest, I profiled this procedure for different `x` (more coming to deviate future impact rate).

Results will follow up...

**Comment by weilbith** [comment]
@berndbohmeier is this enough? Are more benchmarks necessary.

**Comment by weilbith** [comment]
In addition this are the results from applying to a real runtime example. In fact the same code adjustments to the database index configuration have been made and then started the application to synchronize with the actual blockchain. Between each test case all stored data has been removed. In style of the previous tests and to keep it more short, the synchronization has stopped earlier at block 50499 (number relates to the block fetcher window). This are the measured time values:

| index(es) | time |
| --- | --- |
| without | 9:33h |
| only proposer | 6:55h |
| only height | 5:23h |
| both | 4:10h |

**Comment by schmir** [comment]
we need more than 4 hours to synchronize 50499 blocks?

**Comment by weilbith** [comment]
@schmir This is a comparison. My small testing machine was during this time most-likely the whole time on 100% CPU usage. Not sure if the b-tree generation takes all it can or has a maximum, but I guess this could be faster on a machine with more resources. IO was fine and not maxed. 
Feel free to do the same (maybe not with without any index since this is the interesting part) on a much more powerfull machine to see how fast it could be.

**Comment by berndbohmeier** [comment]
Is this a typo? Is it 500k blocks or 50k blocks?

**Comment by weilbith** [comment]
Typo. I'm sorry. Now I also understand @schmir. It is 504.999 blocks.

**Comment by berndbohmeier** [comment]
MMh I dont understand why indexing both is faster, as it should only return one result per block, so there is nothing more to optimize. but well maybe it is like this. I am fine with then just leaving it with the settings to index both.

**Comment by weilbith** [comment]
The only thing I could imagine is that indexing the `proposer` has also an effect to another database interaction. Since our database interface is pretty small as well as only two modules are interacting with it, the number of possibilities is quite small. The three reading functions used are
- `session.query(session.query(Block).exists()).scalar()`
- `session.query(exists().where(Block.hash == block_hash)).scalar()`
- `session.query(Block).filter(Block.proposer == proposer, Block.height == height)`

The last function is the reason for all of this and why we thing having `proposer` indexed as well should not have much impact. So only the first to remains. On first glance I don't see how they could profit by this additional index.
I'll have a look into the documentation and try to find a hint.

**Comment by weilbith** [comment]
Moreover I have a proposal to improve the initial sync even more:
We are using batching to write the blocks into the database. But afterwards we need for ever to make single read queries for each new inserted block. This is the result by using the same design as the `skip_reporter` as well as the `offline_reporter`. As alternative we could use a slightly more complex query once over the whole database to get all rows with duplicate `proposer`, `height` combinations, which could be optimized by the database. This should be definitely faster on initial syncing. Depending on the window size for the continuous fetching of blocks, this could be also efficient all the time. In case this correlates with our requirements to fetch blocks as fast as possible, which would mean to fetch blocks individually, we could introduce a mechanism switch like for the block fetcher, which syncs first forward and then backward.

Query comparison:
As is for each individual block:
```sql
SELECT hash
FROM blocks
WHERE height=100 and proposer="0xb83a..."
```

Alternative after each fetch cycle:
```sql
SELECT hash
FROM blocks
GROUP BY height, proposer
COUNT (*) > 1
```

For the last case I would suggest to think about using a combined index of `height` and `proposer` into a single one. This would lead to less write effort than index both independently and the `GROUP BY` would be not nothing for the database.

**Comment by weilbith** [comment]
Comparison has finished. Since the result supports the current used indexing, the code is not adjusted.
Further tasks like #12 will be implemented to improve the performance even more.
