### ISSUE TITLE
Handle reorg on block before the selected initial block

### ISSUE THREAD

**Issue by weilbith** [trustlines-network/tlbc-monitor#20]
The monitoring service does not handle reorgs on blocks which are based on a block that is older than the initial block the service has started to synchronize from (see `--sync-from` and its default).
As current behavior the service would start to sync backwards until reaching the genesis block. Afterwards (takes very long) it will fail without any meaningful error message. This must be caught earlier and with some useful output.

Related to:
- trustlines-network/project#356

**Comment by weilbith** [comment]
@jannikluhn ideas how we can test this in a practical way? :thinking:

**Comment by jannikluhn** [comment]
With `tester.take_snapshot` and `tester.revert_to_snapshot`. See `test_fetcher.py` for examples.

**Comment by schmir** [comment]
The block is chosen in a way that it's safe from reorgs only affecting the latest MAX_REORG_DEPTH blocks. If we assume this is not safe, the current code fetching the blocks would also need to be fixed (regardless of the initial block).

I'm not sure what we're trying to fix here.

**Comment by jannikluhn** [comment]
The difference is that the old code would fail within seconds, whereas it's 24h or something for the new one.

**Comment by weilbith** [comment]
@schmir would you say this scenario is by the `MAX_REORG_DEPTH` so unlikely that we should ignore it completely? :thinking: 
My thoughts are that first the user has no actual working monitoring service anymore, so he get not informed about new events. And second the user has no clue what happened when the client finally fails.

**Comment by weilbith** [comment]
At least this requirement is not fulfilled:
> ..., but should show a helpful error message

**Comment by schmir** [comment]
If it's likely to happen, I do think we have chosen the wrong value for MAX_REORG_DEPTH. I do think this could happen in practice if someone accidentally starts synchronizing from another chain (i.e. start synchronizing from tlbc and then switch to kovan).

I think you provided some valid arguments here, so feel free to just go on.

**Comment by weilbith** [comment]
>  I do think we have chosen the wrong value for MAX_REORG_DEPTH.

How do you think we could get a better value? Because I think this value is already pretty high. :thinking: 
Nevertheless no value will ever prevent this problem, right?

As I see it the `MAX_REORG_DEPTH` value is a measure to make the initial block selection more safe to prevent this problem happen too often due to the usage of a careless user.
This issue is now about fulfilling the requirements to handle this scenario being recognized it as soon as possible and inform the user about it. Even if this is hopefully not very likely to happen (your example is pretty good! :+1:).
